### ISSUE TITLE
ServiceCircularReferenceException

### ISSUE THREAD

**Issue by jverdeyen** [pixers/PixersDoctrineProfilerBundle#7]
First of all thank you for this bundle.

I've installed the bundle with composer and added it into the AppKernel.
But I'm getting a `ServiceCircularReferenceException`

```
Circular reference detected for service "doctrine.dbal.default_connection", path: "doctrine.dbal.default_connection".
```

I'm using:

- Symfony 3.3.15
- PHP 7.1.2

I couldn't find any alias or re-reference to `doctrine.dbal.default_connection`.
The bundle isn't overriding this id.

Do you have any idea how to further debug this issue?
It's possible that another bundle combined with `PixersDoctrineProfilerBundle`  causes this issue.

Thanks!

**Comment by ojrzenski** [comment]
From what I remember I had the same issue in one project. I think it was related with Doctrine event subscriber - not sure how I managed with that. If don't find any clues in your code - please send some additional info like what doctrine-related bundles you're using or exception stacktrace.

**Comment by jverdeyen** [comment]
Okay, I'll check to disable some bundles and/or Doctrine event subscribers. I'll update the issue afterwards.

**Comment by jverdeyen** [comment]
Found the issue... we injected the `em` into a Doctrine Listener instead of using it from `LifecycleEventArgs`.

derp derp derp derp..
