### ISSUE TITLE
Symfony 4 - The profiler template "PixersDoctrineProfilerBundle:Collector:profiler.html.twig" for data collector "doctrine_profiler" does not exist.

### ISSUE THREAD

**Issue by cristoforocervino** [pixers/PixersDoctrineProfilerBundle#8]
By installing the library on Symfony 4 project the profiler stop loading and show this error message:
```The profiler template "PixersDoctrineProfilerBundle:Collector:profiler.html.twig" for data collector "doctrine_profiler" does not exist.```

**Comment by ghost** [comment]
The issue was fixed in the master branch, but maybe the authors could release a new tagged version of the bundle?

**Comment by cristoforocervino** [comment]
Please! Use tag versions!

**Comment by michallkanak** [comment]
Fixed in https://github.com/pixers/PixersDoctrineProfilerBundle/releases/tag/v1.0.6
Thx!
